CREATE TABLE IF NOT EXISTS identity_saml_connection (
    connection_id               VARCHAR(36)  NOT NULL,
    sp_entity_id                VARCHAR(500),
    acs_url                     VARCHAR(1000),
    idp_entity_id               VARCHAR(500),
    idp_sso_url                 VARCHAR(1000),
    idp_slo_url                 VARCHAR(1000),
    name_id_format              VARCHAR(255) DEFAULT 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
    subject_attribute           VARCHAR(150),
    email_attribute             VARCHAR(150),
    name_attribute              VARCHAR(150),
    groups_attribute            VARCHAR(150),
    sign_authn_requests         INTEGER      NOT NULL DEFAULT 0,
    require_signed_response     INTEGER      NOT NULL DEFAULT 1,
    require_signed_assertion    INTEGER      NOT NULL DEFAULT 1,
    require_encrypted_assertion INTEGER      NOT NULL DEFAULT 0,
    clock_skew_seconds          INTEGER      NOT NULL DEFAULT 60,
    metadata_xml_encrypted      TEXT,
    metadata_fetched_at         BIGINT,
    created_at                  BIGINT       NOT NULL,
    updated_at                  BIGINT       NOT NULL,
    version                     BIGINT       NOT NULL DEFAULT 1,
    PRIMARY KEY (connection_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
