CREATE TABLE IF NOT EXISTS identity_saml_connection (
    connection_id               TEXT    NOT NULL,
    sp_entity_id                TEXT,
    acs_url                     TEXT,
    idp_entity_id               TEXT,
    idp_sso_url                 TEXT,
    idp_slo_url                 TEXT,
    name_id_format              TEXT    DEFAULT 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
    subject_attribute           TEXT,
    email_attribute             TEXT,
    name_attribute              TEXT,
    groups_attribute            TEXT,
    sign_authn_requests         INTEGER NOT NULL DEFAULT 0,
    require_signed_response     INTEGER NOT NULL DEFAULT 1,
    require_signed_assertion    INTEGER NOT NULL DEFAULT 1,
    require_encrypted_assertion INTEGER NOT NULL DEFAULT 0,
    clock_skew_seconds          INTEGER NOT NULL DEFAULT 60,
    metadata_xml_encrypted      TEXT,
    metadata_fetched_at         INTEGER,
    created_at                  INTEGER NOT NULL,
    updated_at                  INTEGER NOT NULL,
    version                     INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (connection_id)
);